export type ERRORS_NAMES =
  | "VALIDATION_ERROR"
  | "CAST_ERROR"
  | "APP_ERROR"
  | "BAD_REQUEST_ERROR"
  | "UNAUTHORIZED_ERROR"
  | "FORBIDDEN_ERROR"
  | "INTERNAL_SERVER_ERROR"
  | "CONFLICT_ERROR"
  | "TOO_MANY_REQUESTS_ERROR"
  | "SERVICE_UNAVAILABLE_ERROR"
  | "DB_ERROR"
  | "DUPLICATE_FIELD"
  | "NOT_FOUND_ERROR";
